config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # localhost:3000/
  # get '/path', to: 'controller#action'
  get '/about_us', to: 'pages#about_us'

  get '/contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact
    @members = ["Francesca", "Johanna", "Denis", "Carolina"]
    if params[:member].nil?
      @members = @members
    else
      @members = @members.select do |member|
        member == params[:member]
      end
    end

    # @today = Date.today
    # @tomorrow = @today + 1 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1>My company</h1>
<p>Some info about what we do...</p>
<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Who are you looking for?">
  <input type="text" name="testing_params" placeholder="Test...">
  <input type="submit">
</form>

app/views/pages/contact.html.erb
<h1>Contact our Team</h1>
<%# <ul>
  <li>Francesca</li>
  <li>Johanna</li>
  <li>Denis</li>
  <li>Carolina</li>
</ul> %>
<ul>
  <% @members.each do |member| %>
    <div class="member-card">
      <li><%= member %></li>
    </div>
  <% end %>
</ul>
<%= params[:testing_params] %>

app/views/shared/_nav.html.erb
<ul>
  <%# <li><a href="">About us</a></li> %>
  <li><%= link_to "About us", about_us_path %></li>
  <%#= localhost:3000/about_us %>
  <%#= mywebsite.com/about_us %>
  <%# <li><a href="">Contact</a></li> %>
  <li><%= link_to "Contact us", contact_path %></li>
  <%#= link_to "Text to display", prefix_path %>
</ul>